### ISSUE TITLE
Update Interface: Display User Address in Top Right Corner

### ISSUE THREAD

**Issue by chopan123** [soroswap/interface#10]
Currently, the user address is stored within the `SorobanContext` object in the Soroswap interface. However, we need to enhance the user experience by displaying the user address in the top right corner of the interface, specifically inside a designated button.

Tasks:

- [x] Extract the user address from the `SorobanContext` object.
- [x] Modify the UI component (e.g., button) in the top right corner of the interface.
- [x] Display the user address inside the button element (once user is connected).
- [x] Ensure that the user address is dynamically updated if it changes during the user's session.
- [x] Apply appropriate styling and formatting to ensure the user address is legible and visually appealing.

Additional Information:
To access the user address, you can utilize the `useSorobanReact` hook provided by `@soroban-react/core`. If you encounter any challenges or have questions about the implementation, please don't hesitate to seek assistance from the development team.

**Comment by esteblock** [comment]
Solved in https://github.com/soroswap/interface/pull/12
